import type { Listing } from "../components/ListingCard";

const now = new Date().toLocaleDateString("tr-TR", { day: "numeric", month: "long", year: "numeric" });

export const mockListings: Listing[] = [
  {
    id: "1",
    title: "Teknoloji Sektöründe Büyüme Ortaklığı",
    type: "Şirket Ortaklığı",
    company: "DigiTech A.Ş.",
    ciro: "₺45M",
    price: "₺2.5M Hisse",
    phone: "+90 532 XXX XX XX",
    desc: "Yapay zeka ve bulut bilişim alanında faaliyet gösteren şirketimize ortak arıyoruz. Yıllık %40 büyüme oranı ile sektörde öncü konumdayız.",
    date: now,
    aiApproved: true,
    owner: "kullanici1",
  },
  {
    id: "2",
    title: "THYAO Hisse Paketi – %4.2 Pay",
    type: "Hisse Satımı",
    company: "Türk Hava Yolları",
    ciro: "₺182B",
    price: "₺890/Hisse",
    phone: "+90 542 XXX XX XX",
    desc: "THYAO hissesinden %4.2 oranında pay satışı. Uzun vadeli yatırım için ideal. Temettü verimi yüksek.",
    date: now,
    aiApproved: true,
    owner: "kullanici2",
  },
  {
    id: "3",
    title: "Gıda Sektöründe Stratejik Ortaklık",
    type: "Şirket Ortaklığı",
    company: "Naturel Gıda Ltd.",
    ciro: "₺12M",
    price: "Ortaklık Payı: ₺800K",
    phone: "+90 535 XXX XX XX",
    desc: "Organik gıda üretiminde Türkiye'nin önde gelen şirketlerinden biri. Yurt dışı pazarlara açılma aşamasındayız.",
    date: now,
    aiApproved: true,
    owner: "kullanici3",
  },
  {
    id: "4",
    title: "E-Ticaret Şirketi Satış",
    type: "Şirket Satışı",
    company: "ShopMax Dijital",
    ciro: "₺28M",
    price: "₺15M",
    phone: "+90 538 XXX XX XX",
    desc: "3 yıldır aktif olan e-ticaret platformu. Aylık 2M+ ziyaretçi, güçlü lojistik altyapı. Tamamı devredilecek.",
    date: now,
    aiApproved: true,
    owner: "kullanici4",
  },
  {
    id: "5",
    title: "GARAN Hisse Alım Fırsatı",
    type: "Hisse Alımı",
    company: "Garanti Bankası",
    ciro: "₺98B",
    price: "₺142/Hisse",
    phone: "+90 541 XXX XX XX",
    desc: "Garanti Bankası hisselerinde büyük alım fırsatı. Piyasa değerinin altında fiyat, analistlerin %30 above hedefi var.",
    date: now,
    aiApproved: true,
    owner: "kullanici5",
  },
  {
    id: "6",
    title: "Lojistik Sektörü Yatırım Ortaklığı",
    type: "Yatırım Ortaklığı",
    company: "FastCargo Lojistik",
    ciro: "₺67M",
    price: "₺4.2M Yatırım",
    phone: "+90 536 XXX XX XX",
    desc: "E-ticaret lojistiğinde hızlı büyüyen şirket. 3 yeni depo açılışı planlanıyor. 5 yıllık projeksiyon ile ROI %250+.",
    date: now,
    aiApproved: false,
    owner: "kullanici6",
  },
];
